-- CreateTable
CREATE TABLE "PACKAGES" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "description" TEXT
);

-- CreateTable
CREATE TABLE "PACKAGE_LOCATIONS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "datetime" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "packageId" INTEGER NOT NULL,
    "cityId" INTEGER NOT NULL,
    CONSTRAINT "PACKAGE_LOCATIONS_packageId_fkey" FOREIGN KEY ("packageId") REFERENCES "PACKAGES" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PACKAGE_LOCATIONS_cityId_fkey" FOREIGN KEY ("cityId") REFERENCES "CITIES" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
