insert into COUNTRIES values (1, 'United States', 'USA');

insert into STATES values ( 1, 'Alabama', 'AL', 1);
insert into STATES values ( 2, 'Alaska', 'AK', 1);
insert into STATES values ( 3, 'Arizona',	'AZ', 1);
insert into STATES values ( 4, 'Arkansas', 'AR', 1);
insert into STATES values ( 5, 'California', 'CA', 1);
insert into STATES values ( 6, 'Colorado', 'CO', 1);
insert into STATES values ( 7, 'Connecticut', 'CT', 1);
insert into STATES values ( 8, 'Delaware', 'DE', 1);
insert into STATES values ( 9, 'Florida', 'FL', 1);
insert into STATES values (10, 'Georgia', 'GA', 1);
insert into STATES values (11, 'Hawaii', 'HI', 1);
insert into STATES values (12, 'Idaho', 'ID', 1);
insert into STATES values (13, 'Illinois', 'IL', 1);
insert into STATES values (14, 'Indiana', 'IN', 1);
insert into STATES values (15, 'Iowa', 'IA', 1);
insert into STATES values (16, 'Kansas', 'KS', 1);
insert into STATES values (17, 'Kentucky', 'KY', 1);
insert into STATES values (18, 'Louisiana', 'LA', 1);
insert into STATES values (19, 'Maine', 'ME', 1);
insert into STATES values (20, 'Maryland', 'MD', 1);
insert into STATES values (21, 'Massachusetts', 'MA', 1);
insert into STATES values (22, 'Michigan', 'MI', 1);
insert into STATES values (23, 'Minnesota', 'MN', 1);
insert into STATES values (24, 'Mississippi', 'MS', 1);
insert into STATES values (25, 'Missouri', 'MO', 1);
insert into STATES values (26, 'Montana', 'MT', 1);
insert into STATES values (27, 'Nebraska', 'NE', 1);
insert into STATES values (28, 'Nevada', 'NV', 1);
insert into STATES values (29, 'New Hampshire', 'NH', 1);
insert into STATES values (30, 'New Jersey', 'NJ', 1);
insert into STATES values (31, 'New Mexico', 'NM', 1);
insert into STATES values (32, 'New York', 'NY', 1);
insert into STATES values (33, 'North Carolina', 'NC', 1);
insert into STATES values (34, 'North Dakota', 'ND', 1);
insert into STATES values (35, 'Ohio', 'OH', 1);
insert into STATES values (36, 'Oklahoma', 'OK', 1);
insert into STATES values (37, 'Oregon', 'OR', 1);
insert into STATES values (38, 'Pennsylvania', 'PA', 1);
insert into STATES values (39, 'Rhode Island', 'RI', 1);
insert into STATES values (40, 'South Carolina', 'SC', 1);
insert into STATES values (41, 'South Dakota', 'SD', 1);
insert into STATES values (42, 'Tennessee', 'TN', 1);
insert into STATES values (43, 'Texas', 'TX', 1);
insert into STATES values (44, 'Utah', 'UT', 1);
insert into STATES values (45, 'Vermont', 'VT', 1);
insert into STATES values (46, 'Virginia', 'VA', 1);
insert into STATES values (47, 'Washington', 'WA', 1);
insert into STATES values (48, 'West Virginia', 'WV', 1);
insert into STATES values (49, 'Wisconsin', 'WI', 1);
insert into STATES values (50, 'Wyoming', 'WY', 1);

insert into CITIES values ( 1, 'Montgomery', 1);
insert into CITIES values ( 2, 'Juneau', 2);
insert into CITIES values ( 3, 'Phoenix',	3);
insert into CITIES values ( 4, 'Little Rock', 4);
insert into CITIES values ( 5, 'Sacramento', 5);
insert into CITIES values ( 6, 'Denver', 6);
insert into CITIES values ( 7, 'Hartford', 7);
insert into CITIES values ( 8, 'Dover', 8);
insert into CITIES values ( 9, 'Tallahassee',	9);
insert into CITIES values (10, 'Atlanta', 10);
insert into CITIES values (11, 'Honolulu', 11);
insert into CITIES values (12, 'Boise', 12);
insert into CITIES values (13, 'Springfield', 13);
insert into CITIES values (14, 'Indianapolis', 14);
insert into CITIES values (15, 'Des Moines',	15);
insert into CITIES values (16, 'Topeka', 16);
insert into CITIES values (17, 'Frankfort', 17);
insert into CITIES values (18, 'Baton Rouge', 18);
insert into CITIES values (19, 'Augusta', 19);
insert into CITIES values (20, 'Annapolis', 20);
insert into CITIES values (21, 'Boston',	21);
insert into CITIES values (22, 'Lansing', 22);
insert into CITIES values (23, 'Saint Paul', 23);
insert into CITIES values (24, 'Jackson', 24);
insert into CITIES values (25, 'Jefferson City', 25);
insert into CITIES values (26, 'Helena', 26);
insert into CITIES values (27, 'Lincoln',	27);
insert into CITIES values (28, 'Carson City', 28);
insert into CITIES values (29, 'Concord', 29);
insert into CITIES values (30, 'Trenton', 30);
insert into CITIES values (31, 'Santa Fe', 31);
insert into CITIES values (32, 'Albany', 32);
insert into CITIES values (33, 'Raleigh',	33);
insert into CITIES values (34, 'Bismarck', 34);
insert into CITIES values (35, 'Columbus', 35);
insert into CITIES values (36, 'Oklahoma City', 36);
insert into CITIES values (37, 'Salem', 37);
insert into CITIES values (38, 'Harrisburg', 38);
insert into CITIES values (39, 'Providence', 39);
insert into CITIES values (40, 'Columbia',	40);
insert into CITIES values (41, 'Pierre', 41);
insert into CITIES values (42, 'Nashville', 42);
insert into CITIES values (43, 'Austin', 43);
insert into CITIES values (44, 'Salt Lake City', 43);
insert into CITIES values (45, 'Montpelier', 45);
insert into CITIES values (46, 'Richmond',	46);
insert into CITIES values (47, 'Olympia', 47);
insert into CITIES values (48, 'Charleston', 48);
insert into CITIES values (49, 'Madison', 49);
insert into CITIES values (50, 'Cheyenne', 50);
