-- CreateTable
CREATE TABLE "CITIES" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "acronym" TEXT NOT NULL,
    "stateId" INTEGER NOT NULL,
    CONSTRAINT "CITIES_stateId_fkey" FOREIGN KEY ("stateId") REFERENCES "STATES" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "STATES" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "acronym" TEXT NOT NULL,
    "countryId" INTEGER NOT NULL,
    CONSTRAINT "STATES_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "COUNTRIES" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "COUNTRIES" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "acronym" TEXT NOT NULL
);
